### ISSUE TITLE
Suporte para 1.13

### ISSUE THREAD

**Issue by EverNife** [RUSHyoutuber/MambaFactions#1]
Salve!
Gostaria de saber se vai demorar muito para colocar suporte para a versão 1.13

Eu iria abrir um servidor factions nesse final de semana, mas como saiu o Minecraft 1.13 haha ai nem vale mais a pena abrir na 1.12

Existe alguma estimativa para a atualização? Porque se não for demorar muito ai vale mais a pena para mim esperar.

**Comment by eduardo-mior** [comment]
Olá! Desculpa pela demora...
A atualização para a 1.13 não é por minha conta infelizmente :(
Eu dei uma estudada e pelo que eu vi é muito complexo adaptar todo o massivecore para a 1.13 então irei deixar para o pessoal da massive trabalhar com isso ><

Há também uma chance de que eles não deem suporte para a 1.13 e há também uma chance de que eles abandonem as versões anteriores e fiquem só com 1.13... estou aguardando o pessoal da massive.

**Comment by eduardo-mior** [comment]
Ainda estou esperando o pessoal do Massive lançar a compatibilidade com 1.13.

**Comment by eduardo-mior** [comment]
Acabei de receber a noticia de que o Factions lançou um novo projeto para 1.13 e abandonou o antigo, segue o link do novo projeto: https://www.spigotmc.org/resources/factions3-for-1-13.63602/
Não pretendo atualizar o Mamba para 1.13
