### ISSUE TITLE
WorldGuard Integration

### ISSUE THREAD

**Issue by EverNife** [RUSHyoutuber/MambaFactions#2]
Uma sugestão em para melhora o relacionamento com um dos plugins de proteção mais usados do bukkit.

1- Jogadores não podem conquistar uma região com wordlguard
   \--> (poderia ser feito uma flag para que ele possa, sei lá, "/rg flag <name> factions-claim allow"
   \--> Ou caso dê muito trabalho e queira fazer algo mais simples, verificar se o jogador pode construir no local

**Comment by eduardo-mior** [comment]
Acho que isso é trabalho para outros... não tenho muita experiencia com API do WorldGuard ou outros plugins de proteção. Vale lembrar também que nem todo mundo usa esse tipo de plugin e se essa ideia fosse mal implementada poderia gerar lag.

Estou fazendo faculdade e o tempo para trabalhar com Bukkit é pouco :(
