### ISSUE TITLE
Adicionar suporte a maven.

### ISSUE THREAD

**Issue by mtbarr** [RUSHyoutuber/MambaFactions#5]
O plugin não contem nenhum gerenciador de dependencias, assim ficando totalmente inutil para ser utilizado como dependencia juntamente com outros plugins.

**Comment by eduardo-mior** [comment]
A questão do gerenciador de dependências não deve ser engessada ao projeto.
Cada desenvolver é livre para usar o gerenciador de dependências que quiser, por isso eu não implementei nenhum no projeto e optei por fazer manualmente.
Se você quiser implementar maven ou qualquer outro alternativo sinta-se livre. Se quiser abrir um PR também eu irei aceitar com prazer.

**Comment by mtbarr** [comment]
Mas o projeto usa classpath do eclipse, não tem como só inserir um novo gerenciador de depêndencias.

**Comment by eduardo-mior** [comment]
Sim, mas no caso, vc pode apagar o classpath do eclipse e trabalhar com maven. Eu na época commitei o classpath por burrice na verdade, porque ele não tem necessidade e nem deveria estar ali.
O certo nesse caso era ter um readme ensinando a rodar o projeto tanto com maven quanto com outros gerenciadores de dependencias, mas como eu não tinha experiência na area e a grande maioria dos devs usava eclipse então acabei deixando por assim mesmo.
Mas se quiser vc pode fazer com maven e fazer um PR.
